### ISSUE TITLE
xcode update breaking the build

### ISSUE THREAD

**Issue by goodliff** [imkira/cukunity#3]
Hi, 

We've just started updating xcode to the new version and have noticed some build errors when we include cukunity. Have you noticed similar issues? 

I'm waiting for the error log from our developers and will add that as soon as I can.

**Comment by goodliff** [comment]
The logs are as follows:

/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:68:9: Use of undeclared identifier '_tapCount'; did you mean 'tapCount'?
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:69:9: Use of undeclared identifier '_locationInWindow'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:70:9: Use of undeclared identifier '_previousLocationInWindow'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:70:37: Use of undeclared identifier '_locationInWindow'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:72:47: Use of undeclared identifier '_locationInWindow'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:73:9: Use of undeclared identifier '_window'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:74:9: Use of undeclared identifier '_view'; did you mean 'view'?
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:75:9: Use of undeclared identifier '_phase'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:76:9: Use of undeclared identifier '_touchFlags'
/Users/Shared/STM/Unity/abc/Libraries/CukunityServer.mm:77:9: Use of undeclared identifier '_touchFlags'

**Comment by Arguas** [comment]
For anyone who still sees this issue and is looking for a workaround, have a look here:

http://stackoverflow.com/questions/12724233/simulating-uitouch-in-xcode-4-5-programmatically-uispec

When you build a Unity game through iOS, you will need to add in these lines to your CukunityServer.mm file, in the following way:

@interface UITouch (Synthesize)
- (id)initInView:(UIView *)view;
- (void)setPhase:(UITouchPhase)phase;
- (void)setLocationInWindow:(CGPoint)location;

@end

#ifdef __IPHONE_6_0
@interface UITouch () {
    NSTimeInterval _timestamp;
    UITouchPhase _phase;
    UITouchPhase _savedPhase;
    NSUInteger _tapCount;

```
UIWindow *_window;
UIView *_view;
UIView *_gestureView;
UIView *_warpedIntoView;
NSMutableArray *_gestureRecognizers;
NSMutableArray *_forwardingRecord;

CGPoint _locationInWindow;
CGPoint _previousLocationInWindow;
UInt8 _pathIndex;
UInt8 _pathIdentity;
float _pathMajorRadius;
struct {
    unsigned int _firstTouchForView:1;
    unsigned int _isTap:1;
    unsigned int _isDelayed:1;
    unsigned int _sentTouchesEnded:1;
    unsigned int _abandonForwardingRecord:1;
} _touchFlags;
```

}
@end
#endif

**Comment by imkira** [comment]
Sorry for the huge delay.

@Arguas, thanks for the contribution.
I have also added the missing private definitions and commited.
I haven't still made a gem out of it but it is in the HEAD. Please let me know if it works.
